/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuelstation;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rasha
 */
public class Fuel extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form Fuel
     */
    public Fuel() {
        super("Fuel");
        initComponents();
        conn =DBconnection.connect();
        fillTable();
        fillJComboBox1();
    }
    
     //Fill Employee number
    public void fillJComboBox1() {
        String sql="select p_num from pump";
        try{
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            jComboBox1.addItem("Select Pump ID");
            while(rs.next()){
                jComboBox1.addItem(rs.getString("p_num"));  
            }
            pst.close();  
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something Wrong !!");
        }   
    }
     // Fill pump table
    public void fillTable(){
        DefaultTableModel model = new DefaultTableModel(new String[]{ "ID","Type", "Liters Price","Amount"}, 0);
        try{
            String sql="SELECT f_id,f_type,liters_price,amount FROM fuel;";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            while(rs.next()){
                String a = rs.getString("f_id");
                String e = rs.getString("f_type");
                String f = rs.getString("liters_price");
                String h = rs.getString("amount");
                model.addRow(new Object[]{ a,e, f , h});
            }         
            jTable1.setModel(model);
            pst.close();  
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something Error, Please try Later!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("All Fuels");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rasha\\Documents\\NetBeansProjects\\FuelStation\\images\\fuels.png")); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Liter Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Show Fuels in pump");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Show selling fuel in pump");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(2, 2, 2)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Type");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Amount");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Pump no");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(15, 15, 15))
        );

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 3, 36)); // NOI18N
        jLabel1.setText("Fuels");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home was=new Home();
        was.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton4.setVisible(true);
//        jButton5.setVisible(true);
        fillTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int rowId=jTable1.getSelectedRow();
        if(rowId==-1){
            JOptionPane.showMessageDialog(null, "Please Selected Row!");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        String type=model.getValueAt(rowId,1).toString();
        String litersPrice=model.getValueAt(rowId,2).toString();
        if(type.length()<2||type==""||litersPrice.length()<1||litersPrice==""){
               JOptionPane.showMessageDialog(null, "Error Input");
                fillTable();
                return;
        }        
        fillTable();
        DefaultTableModel model2=(DefaultTableModel)jTable1.getModel();
        int fuelId=Integer.parseInt(model2.getValueAt(rowId,0).toString());
        String oldFuelName=model2.getValueAt(rowId,1).toString();
        try{
            String sql2="UPDATE fuel SET f_type=?,liters_price=? WHERE f_id=?";
            pst=conn.prepareStatement(sql2);
            pst.setString(1,  type);
            pst.setString(2, litersPrice);
            pst.setInt(3, fuelId);
            pst.execute();
            pst.close(); 
            
            String sql3="UPDATE fuel_pump SET f_type=? WHERE f_type=?";
            pst=conn.prepareStatement(sql3);
            pst.setString(1,  type);
            pst.setString(2, oldFuelName);
            pst.execute();
            pst.close(); 
            
            String sql4="UPDATE sale_fuel SET f_type=? WHERE f_type=?";
            pst=conn.prepareStatement(sql4);
            pst.setString(1,  type);
            pst.setString(2, oldFuelName);
            pst.execute();
            pst.close(); 
                     
            fillTable();
            pst.close();  
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sorry!! Something wrong !!");
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          try{
              if(jTextField1.getText().length()<2|| jTextField1.getText()==""||jTextField2.getText()==""||jComboBox1.getSelectedIndex()==0|| jTextField2.getText().length()<1){
                JOptionPane.showMessageDialog(null, "Error Input");
                jTextField2.setText("");
                jComboBox1.setSelectedIndex(0);
                jTextField1.setText("");
                return;
            }
            int pumpId= Integer.parseInt(jComboBox1.getSelectedItem().toString());
            String ftype=jTextField1.getText();
            int amount= Integer.parseInt(jTextField2.getText());
            
            String sql5="SELECT SUM(b_amount) as allFuel FROM fuel_pump where p_num=?;";
            pst=conn.prepareStatement(sql5);
            pst.setInt(1, pumpId);
            rs= pst.executeQuery();
            int fuelInPump=0;
            if(rs.next()){
                fuelInPump=rs.getInt("allFuel")+amount;
                pst.close();
                rs.close();
                
                String sql6="SELECT volume FROM pump where p_num=?;";
                pst=conn.prepareStatement(sql6);
                pst.setInt(1, pumpId);
                rs= pst.executeQuery();
                if(rs.next()){
                  int pumnVolumn=rs.getInt("volume");
                    if(fuelInPump>pumnVolumn){
                        JOptionPane.showMessageDialog(null, "Volumn of pump isn't enough to add this amount ");
                        jTextField2.setText("");
                        jComboBox1.setSelectedIndex(0);
                        jTextField1.setText("");
                        return;
                    }  
                } 
                pst.close();
                rs.close();
            }
            
            String sql2="select f_type from fuel_pump Where f_type=? and p_num=?";
            pst=conn.prepareStatement(sql2);
            pst.setString(1, jTextField1.getText());
            pst.setInt(2, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            rs= pst.executeQuery();
            if(rs.first()){
                pst.execute();
                pst.close(); 
                String sql3="UPDATE fuel_pump SET b_amount=b_amount+? WHERE f_type=? and p_num=?";
                pst=conn.prepareStatement(sql3);
                pst.setInt(1, Integer.parseInt(jTextField2.getText()));
                pst.setString(2, jTextField1.getText());
                pst.setInt(3, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
                pst.execute();
                pst.close(); 
            }else{
                pst.execute();
                pst.close(); 
                 String sql3="insert into fuel_pump(p_num,f_type,b_amount)values(?,?,?)";
                pst=conn.prepareStatement(sql3);
                pst.setInt(1, pumpId );
                pst.setString(2, ftype);
                pst.setInt(3,amount);
                pst.execute();
                pst.close();
            }
            
           String sql="select f_type from fuel Where f_type=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, jTextField1.getText());
            rs= pst.executeQuery();
            if(rs.first()){
                pst.execute();
                pst.close(); 
                String sql3="UPDATE fuel SET amount=amount+? WHERE f_type=?";
                pst=conn.prepareStatement(sql3);
                pst.setInt(1, Integer.parseInt(jTextField2.getText()));
                pst.setString(2, jTextField1.getText());
                pst.execute();
                pst.close(); 
            }else{
                pst.execute();
                pst.close(); 
                String sql4="insert into fuel(f_type,liters_price,amount)values(?,?,?)";
                pst=conn.prepareStatement(sql4);
                pst.setString(1, jTextField1.getText());
                pst.setString(2,"5");
                pst.setString(3,jTextField2.getText());
                pst.execute();
                pst.close(); 
            }
            
            JOptionPane.showMessageDialog(null, "Fuel Added");
            jTextField2.setText("");
            jTextField1.setText("");
            jComboBox1.removeAllItems();
            fillJComboBox1();
            fillTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            if(Integer.parseInt(jTextField3.getText()) ==0 || Integer.parseInt(jTextField3.getText())<0 || jTextField3.getText()==""){
                JOptionPane.showMessageDialog(null, "Wrong Input!");
                jTextField3.setText("");
                return;
            }
            String sql="select p_num from pump";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            boolean found=false;
            while(rs.next()){
                 if(Integer.parseInt(rs.getString("p_num"))==Integer.parseInt(jTextField3.getText()))
                     found=true; 
            }
            pst.close();  
            rs.close();
            if(found==true){
            DefaultTableModel model = new DefaultTableModel(new String[]{"Pump No", "Fuel Type", "Amount"}, 0);
            String sql2="SELECT p_num,f_type,b_amount FROM fuel_pump Where p_num =?;";
            pst=conn.prepareStatement(sql2);
            pst.setString(1,jTextField3.getText());
            rs= pst.executeQuery();
         //  model.addRow(new Object[]{"No Data"});
            while(rs.next()){
                    String a = rs.getString("p_num");
                    String e = rs.getString("f_type");
                    String f = rs.getString("b_amount");
                    model.addRow(new Object[]{a, e, f});
                }
            jButton4.setVisible(false);
//            jButton5.setVisible(false);
            jTable1.setModel(model);
            pst.close();  
            rs.close();
            found=false;
            jTextField3.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error Input!");
                jTextField3.setText("");
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            if(Integer.parseInt(jTextField3.getText()) ==0 || Integer.parseInt(jTextField3.getText())<0 || jTextField3.getText()==""){
                JOptionPane.showMessageDialog(null, "Wrong Input!");
                jTextField3.setText("");
                return;
            }
            String sql="select p_num from pump";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            boolean found=false;
            while(rs.next()){
                 if(Integer.parseInt(rs.getString("p_num"))==Integer.parseInt(jTextField3.getText()))
                     found=true; 
            }
            pst.close();  
            rs.close();
            if(found==true){
            DefaultTableModel model = new DefaultTableModel(new String[]{"Pump No","Person Card", "Fuel Type", "Amount","Date","Price"}, 0);
            String sql2="SELECT p_num,person_card,f_type,sale_amount,date,price FROM sale_fuel Where p_num =?;";
            pst=conn.prepareStatement(sql2);
            pst.setString(1,jTextField3.getText());
            rs= pst.executeQuery();
         //  model.addRow(new Object[]{"No Data"});
            while(rs.next()){
                    String a = rs.getString("p_num");
                    String e = rs.getString("person_card");
                    String f = rs.getString("f_type");
                    String g = rs.getString("sale_amount");
                    String h = rs.getString("date");
                    String l = rs.getString("price");
                    model.addRow(new Object[]{a, e, f,g,h,l});
                }
            jButton4.setVisible(false);
       //     jButton5.setVisible(false);
            jTable1.setModel(model);
            pst.close();  
            rs.close();
            found=false;
            jTextField3.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error Input!");
                jTextField3.setText("");
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                                       
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
