/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuelstation;

import java.sql.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rasha
 */
public class Pump extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form Box
     */
    public Pump() {
        super("Pump");
        initComponents();
        conn =DBconnection.connect();
        fillJComboBox1();
        fillTablePump();
    }
    
    // Fill pump table
    public void fillTablePump(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"Pump No", "Employee Name", "Volume"}, 0);
        try{
            String sql="SELECT pump.p_num,name,volume FROM pump INNER JOIN employee ON pump.employee_id=employee.id;";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            while(rs.next()){
                String d = rs.getString("pump.p_num");
                String e = rs.getString("name");
                String f = rs.getString("volume");
                model.addRow(new Object[]{d, e, f});
                
            }
            jTable1.setModel(model);
            pst.close();  
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something Error, Please try Later!");
        }
    }
   //Fill Employee number
    public void fillJComboBox1() {
        try{
            String sql1="SELECT id,name FROM employee;";
            pst=conn.prepareStatement(sql1);
            rs= pst.executeQuery();
            int employeeId=0;
            String employeeName="";
            jComboBox1.addItem("Select Employee Name");
            while(rs.next()){
                boolean found=false;
                employeeId=rs.getInt("id");
                employeeName=rs.getString("name");
                                
                String sql3="select employee_id from pump where employee_id=?";
                pst=conn.prepareStatement(sql3);
                pst.setInt(1, employeeId );
                if(pst.executeQuery().first())found=true;
                
                String sql4="select employee_id from washer where employee_id=?";
                pst=conn.prepareStatement(sql4);
                pst.setInt(1, employeeId );
                if(pst.executeQuery().first())found=true;
                if(found==false)
                jComboBox1.addItem(employeeName);   
            }
            pst.close();  
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Something Wrong !!");
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("L");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Pump Volumn");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Employee Name");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Show all car refuel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Show all fuel sales");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Emplpyee Name", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("All Pumps");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rasha\\Documents\\NetBeansProjects\\FuelStation\\images\\Box.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 2, 36)); // NOI18N
        jLabel1.setText("Pump");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jButton6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton5))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3)
                                        .addComponent(jLabel3))))
                            .addGap(77, 77, 77)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(9, 9, 9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(56, 56, 56)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ho=new Home();
        ho.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton6.setVisible(true);
        jButton5.setVisible(true);
        fillTablePump();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            if(jTextField1.getText().length()<1||jComboBox1.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Error Input");
                jComboBox1.setSelectedIndex(0);
                jTextField1.setText("");
                return;
            }
            String sql="select id from employee where name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, (String)jComboBox1.getSelectedItem() );
            rs= pst.executeQuery();
            String Id="";
            if(rs.next()){
                Id=rs.getString("id");
            }
            pst.close();
            rs.close();
            String sql2="insert into pump(employee_id,volume)values(?,?)";
            pst=conn.prepareStatement(sql2);
            pst.setString(1,Id );
            pst.setString(2, jTextField1.getText());
            pst.execute();
            pst.close();
            jComboBox1.removeAllItems();
            fillJComboBox1();
            jTextField1.setText("");
          //  DefaultTableModel mod=(DefaultTableModel)jTable1.getModel();
           // mod.setRowCount(0);
            fillTablePump();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Something Error, Please Try Later!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int rowId=jTable1.getSelectedRow();
        if(rowId==-1){
            JOptionPane.showMessageDialog(null, "Please Selected Row!");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        if(model.getValueAt(rowId,0).toString()==""){
            JOptionPane.showMessageDialog(null, "Error Row!");
            return;
        }
        int pumpId=Integer.parseInt(model.getValueAt(rowId,0).toString());
        try{
            String sql4="select id from sale_fuel where p_num =?";
            pst=conn.prepareStatement(sql4);
            pst.setString(1, model.getValueAt(rowId,0).toString());
            rs= pst.executeQuery();
            if(rs.first()){
                JOptionPane.showMessageDialog(null, "Sorry you can't delete this Pump!");
                pst.close();  
                rs.close();
                return;                  
            }
            pst.close();  
            rs.close();
            
            String sql3="select id from fuel_pump where p_num =?";
            pst=conn.prepareStatement(sql3);
            pst.setString(1, model.getValueAt(rowId,0).toString());
            rs= pst.executeQuery();
            if(rs.first()){
                JOptionPane.showMessageDialog(null, "Sorry you can't delete this Pump!");
                pst.close();  
                rs.close();
                return;                  
            }
            pst.close();  
            rs.close();
            
            String sql="select id from car_pump where p_num =?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, model.getValueAt(rowId,0).toString());
            rs= pst.executeQuery();
            if(rs.first()){
                JOptionPane.showMessageDialog(null, "Sorry you can't delete this Pump!");
                pst.close();  
                rs.close();
                return;                  
            }
            pst.close();  
            rs.close();
            
            String sql2="Delete from pump where p_num=?";
            pst=conn.prepareStatement(sql2);
            pst.setInt(1, pumpId);
            pst.execute();
            fillTablePump();
            pst.close();  
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sorry!! Something wrong !!");
        }   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
            if(Integer.parseInt(jTextField2.getText()) ==0 || Integer.parseInt(jTextField2.getText())<0 || jTextField2.getText()==""){
                JOptionPane.showMessageDialog(null, "Wrong Input!");
                jTextField2.setText("");
                return;
            }
            String sql="select p_num from pump";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            boolean found=false;
            while(rs.next()){
                 if(Integer.parseInt(rs.getString("p_num"))==Integer.parseInt(jTextField2.getText()))
                     found=true; 
            }
            pst.close();  
            rs.close();
            if(found==true){
            DefaultTableModel model = new DefaultTableModel(new String[]{ "Pump No","Car No", "Type", "Amount","Date","Price"}, 0);
            String sql2="SELECT p_num,c_num,f_type,c_amount,date,price FROM car_pump Where p_num =?;";
            pst=conn.prepareStatement(sql2);
            pst.setString(1,jTextField2.getText());
            rs= pst.executeQuery();
         //  model.addRow(new Object[]{"No Data"});
            while(rs.next()){
                    String a = rs.getString("p_num");
                    String d = rs.getString("c_num");
                    String e = rs.getString("f_type");
                    String f = rs.getString("c_amount");
                    String h = rs.getString("date");
                    String g = rs.getString("price");
                    model.addRow(new Object[]{a,d, e, f,h,g});
                }
            jButton6.setVisible(false);
            jButton5.setVisible(false);
            jTable1.setModel(model);
            pst.close();  
            rs.close();
            found=false;
            jTextField2.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error Input!");
                jTextField2.setText("");
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Something Error, Please Try Later!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       int rowId=jTable1.getSelectedRow();
        if(rowId==-1){
            JOptionPane.showMessageDialog(null, "Please Selected Row!");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        String employeeName=model.getValueAt(rowId,1).toString();
        String volumn=model.getValueAt(rowId,2).toString();
        if(employeeName.length()<2||volumn.length()<1){
            JOptionPane.showMessageDialog(null, "Error Input");
            fillTablePump();
            return;
        }
        fillTablePump();
        DefaultTableModel model2=(DefaultTableModel)jTable1.getModel();
        int pumpId=Integer.parseInt(model2.getValueAt(rowId,0).toString());
        String oldname=model2.getValueAt(rowId,1).toString();
        
        try{
           String sql="select id,name from employee where name =?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, employeeName);
            rs= pst.executeQuery();
            if(!rs.first()){                
                JOptionPane.showMessageDialog(null, "Sorry, No employee!");
                
                pst.close();  
                rs.close();
                return;                  
            }  
            int employeeId=rs.getInt("id");
            pst.close();  
            rs.close();
            if(!oldname.equals(employeeName)){
             String sql3="select employee_id from pump where employee_id=? ";
            pst=conn.prepareStatement(sql3);
            pst.setInt(1, employeeId );
                
            if(pst.executeQuery().first()){
                JOptionPane.showMessageDialog(null, "Sorry, You Can't Editing!");
                pst.close();  
                rs.close();
                return; 
            }
            pst.close();  
            rs.close(); 
                
            String sql4="select employee_id from washer where employee_id=?";
            pst=conn.prepareStatement(sql4);
            pst.setInt(1, employeeId );
            
            if(pst.executeQuery().first()){
                JOptionPane.showMessageDialog(null, "Sorry, You Can't Editing");
                pst.close();  
                rs.close();
                return; 
            }
            pst.close();  
            rs.close();
            String sql2="UPDATE pump SET employee_id=?,volume=? WHERE p_num=?";
            pst=conn.prepareStatement(sql2);
            pst.setInt(1,  employeeId);
            pst.setString(2, volumn);
            pst.setInt(3, pumpId);
            pst.execute();
            fillTablePump();
            pst.close();  
            rs.close();
            }else{                
                String sql6="UPDATE pump SET volume=? WHERE p_num=?";
                pst=conn.prepareStatement(sql6);
                pst.setString(1, volumn);
                pst.setInt(2, pumpId);
                pst.execute();
                fillTablePump();
                pst.close();  
                rs.close();
            }          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Sorry!! Something wrong !!");
        }   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            if(Integer.parseInt(jTextField2.getText()) ==0 || Integer.parseInt(jTextField2.getText())<0 || jTextField2.getText()==""){
                JOptionPane.showMessageDialog(null, "Wrong Input!");
                jTextField2.setText("");
                return;
            }
            String sql="select p_num from pump";
            pst=conn.prepareStatement(sql);
            rs= pst.executeQuery();
            boolean found=false;
            while(rs.next()){
                 if(Integer.parseInt(rs.getString("p_num"))==Integer.parseInt(jTextField2.getText()))
                     found=true; 
            }
            pst.close();  
            rs.close();
            if(found==true){
            DefaultTableModel model = new DefaultTableModel(new String[]{ "Pump No","Person Card", "Type", "Amount","Date","Price"}, 0);
            String sql2="SELECT p_num,person_card,f_type,sale_amount,date,price FROM sale_fuel Where p_num =?;";
            pst=conn.prepareStatement(sql2);
            pst.setString(1,jTextField2.getText());
            rs= pst.executeQuery();
         //  model.addRow(new Object[]{"No Data"});
            while(rs.next()){
                    String a = rs.getString("p_num");
                    String d = rs.getString("person_card");
                    String e = rs.getString("f_type");
                    String f = rs.getString("sale_amount");
                    String h = rs.getString("date");
                    String g = rs.getString("price");
                    model.addRow(new Object[]{a,d, e, f,h,g});
                }
            jButton6.setVisible(false);
            jButton5.setVisible(false);
            jTable1.setModel(model);
            pst.close();  
            rs.close();
            found=false;
            jTextField2.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error Input!");
                jTextField2.setText("");
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
